services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./.volume:/root/.ollama
    entrypoint: ["/bin/sh", "-c", "ollama serve & sleep 3 && ollama pull mistral:instruct && wait"]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - ollama
