services:
  ollama:
    image: ollama/ollama
    container_name: pb-ollama
    ports:
      - "11434:11434"
    volumes:
      - ./.volume-ollama:/root/.ollama
    entrypoint: ["/bin/sh", "-c", "ollama serve & sleep 3 && ollama pull mistral:instruct && wait"]

  db:
    image: postgres:17
    container_name: pb-db
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
      POSTGRES_DB: tasks
    volumes:
      - ./.volume-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pb-backend
    depends_on:
      - ollama
      - db
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pb-frontend
    depends_on:
      - backend
    ports:
      - "8501:8501"
