[project]
name = "procrastinationbuddy"
version = "0.1.0"
description = "Finds lame excuses for doing boring tasks - more fun-time for you."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.0",
    "psycopg2-binary>=2.9.10",
    "requests>=2.32.3",
    "ruff>=0.11.7",
    "sqlalchemy>=2.0.40",
]
