name: Quality Gate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  gate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run Ruff Linter in backend
        working-directory: ./backend
        run: |
          ruff check .

      - name: Run Ruff Linter in frontend
        working-directory: ./frontend
        run: |
          ruff check .

      - name: Docker Compose
        run: |
          docker compose pull
          docker compose up --build --force-recreate --detach
          cd e2e-tests
          ./npmw ci
          ./npmw run install
          ./npmw run test

      - name: Publish Playwright Test Results
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: always()
        with:
          check_name: "Playwright UI Tests"
          files: ./e2e-tests/test-results/results.xml

      - name: Archive Playwright Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report.zip
          path: ./e2e-tests/test-results
          retention-days: 7
